;;;; -*- mode: common-lisp;   common-lisp-style: modern;    coding: utf-8; -*-
;;;;
;;;; Screamer-Plus: A modernized constraint logic programming library for Common Lisp
;;;;
;;;; Screamer-Plus is an extension of constraint propagation in Screamer,
;;;; built upon a fundamental redesign of the core functions `funcallv` and `applyv`
;;;; introduced in version 4.0.1 of Screamer.
;;;;
;;;; This new foundation enables automatic constraint propagation, eliminating the
;;;; need for manual noticers and simplifying function/macro definitions.
;;;; As a result, many of the macros and functions originally found in Screamer-Plus
;;;; (by Simon White) — such as `CARV`, `CDRV`, `IFV`, and others — have been
;;;; entirely rewritten or reimagined with cleaner semantics and greater efficiency.
;;;;
;;;; Some function names and general ideas are inspired by the original Screamer-Plus
;;;; by Simon White, but all code in this package is original unless otherwise noted.”
;;;;
;;;; Contributions, feedback, and extensions are welcome.
;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;
;;;; Copyright (c) 2025 Paulo Henrique Raposo
;;;;
;;;; Permission is hereby granted, free of charge, to any person obtaining a copy of
;;;; this software and associated documentation files (the "Software"), to deal in
;;;; the Software without restriction, including without limitation the rights to
;;;; use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
;;;; the Software, and to permit persons to whom the Software is furnished to do so,
;;;; subject to the following conditions:
;;;;
;;;; The above copyright and authorship notice and this permission notice shall be
;;;; included in all copies or substantial portions of the Software.
;;;;
;;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
;;;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
;;;; FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
;;;; COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
;;;; IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
;;;; CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#+allegro
(setq excl:*redefinition-warnings* (remove :operator excl:*redefinition-warnings*))

#+sbcl
(setq sb-ext:*redefinition-warnings* nil)

#+lispworks
(setf lw::*handle-warn-on-redefinition* :nil) 

#+ccl
(setq ccl:*warn-if-redefine* nil)

(in-package :screamer)

(defun objectp (var)
  "Determines whether a variable is a standard CLOS object or not"
  (typep var 'standard-object))

(defun slot-names-of (obj)
  (mapcar #'closer-mop:slot-definition-name
          (closer-mop:class-slots (class-of obj))))

(defun copy-standard-object (obj)
  "Shallow copy of a CLOS object (standard-object)."
  (let* ((class (class-of obj))
         (copy (make-instance class)))
    (dolist (slot (slot-names-of obj))
      (setf (slot-value copy slot) (slot-value obj slot)))
    copy))

 (defun variables-in (x)
  (the list
   (let ((x (value-of x)))
       ;; Note: (value-of x) is required to dereference a variable 
       ;; whose value has been unified (using EQUALV) with other 
       ;; data types, such as cons cells, lists, and so on.
       (typecase x
         (cons (append (variables-in (car x))
                       (variables-in (cdr x))))
         (string nil)
         ;; (simple-vector (apply #'append (map 'list #'variables-in x)))
         (sequence (apply #'append (map 'list #'variables-in x)))
         (array (flet ((mappend-arr (arr f)
                         (let (coll)
                           (dotimes (idx (array-total-size arr))
                             (alexandria::appendf coll (funcall f (row-major-aref arr idx))))
                           coll)))
                  (mappend-arr x #'variables-in)))
         (hash-table (let (coll)
                       (maphash (lambda (k v)
                                  (declare (ignore k))
                                  (alexandria::appendf coll (variables-in v)))
                                x)
                       coll))
         (standard-object (let (coll)
                           (dolist (slot (slot-names-of x))
                            (alexandria:appendf coll (variables-in (slot-value x slot))))
                            coll))
         (variable (list x))
         (otherwise nil)))))

(defun apply-substitution (x)
  "If X is a SEQUENCE or HASH-TABLE, returns a freshly consed
copy of the tree with all variables dereferenced.
Otherwise returns the value of X."
  (let ((x (value-of x)))
    (etypecase x
      (cons (if (null (cdr (last x)))
                ;; If terminates with nil (ie normal list)
                ;; use mapcar to not consume stack
                (mapcar #'apply-substitution x)
                ;; Otherwise recurse on the car and cdr
                (cons (apply-substitution (car x))
                      (apply-substitution (cdr x)))))
      (string x)
      (simple-vector (map 'vector #'apply-substitution x))
      (sequence (let ((copy (copy-seq x)))
                  (dotimes (idx (length x))
                    (setf (elt copy idx)
                          (apply-substitution (elt x idx))))
                  copy))
      (array (let ((arr (alexandria::copy-array x)))
               (dotimes (idx (array-total-size arr))
                 (setf (row-major-aref arr idx)
                       (apply-substitution (row-major-aref arr idx))))
               arr))
      (hash-table
       (let ((x (alexandria::copy-hash-table x)))
         (maphash (lambda (k v) (setf (gethash k x) (apply-substitution v))) x)
         x))
       (standard-object (let ((copy (copy-standard-object x)))
                              (dolist (slot (slot-names-of x))
                                (setf (slot-value copy slot)
                                      (apply-substitution (slot-value x slot))))
                              copy))
      (t x))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; NEW TYPES OF VARIABLES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun proper-listp (obj)
;; Note: will LOOP if obj is a circular list
 (typecase obj
  (list (null (cdr (last obj))))
  (otherwise nil)))

(defun canonical-type (obj)
  (typecase obj
    (integer 'integer)
    (ratio 'ratio)
    (float 'float)
    (complex 'complex)
    (boolean 'boolean)
    (symbol 'symbol)
    (cons (if (proper-listp obj) 'list 'cons))
    (string 'string)
    (simple-vector 'vector)
    (array 'array)
    (sequence 'sequence)
    (hash-table 'hash-table)
    (standard-object 'standard-object)
    (character 'character)
    (variable 'variable)
    (t (type-of obj))))

(defun print-variable (x stream print-level)
   (declare (ignore print-level)) 
  (let ((name (variable-name x))
        (x (value-of x)))
    (cond
      ((variable? x)
       (if (and (not (eq (variable-enumerated-domain x) t))
                (not (null (variable-enumerated-antidomain x))))
           (error "This shouldn't happen"))
       (format stream "[~S" name)
      (format stream "~A"
        (cond
          ((variable-boolean? x) " Boolean")
          ((variable-real? x)
          (cond
            ((variable-rational? x)
              (cond
                ((variable-integer? x) " integer")
                ((variable-noninteger-rational? x) " noninteger-rational")
                (t " rational")))
            (t
              (cond
                ((variable-noninteger? x)
                 (if (variable-nonrational? x)
                      " nonrational-real" " noninteger-real"))
                (t " real")))))
                     ((variable-number? x)
                      (cond ((variable-nonreal? x) " nonreal-number")
                            ((variable-noninteger? x) " noninteger-number")
                            ((variable-nonrational? x) " nonrational-number")
                            ((variable-rational? x) " rational-number")
                            (t " number")))
                     ((variable-nonnumber? x)
                      (cond ((and (not (eq (variable-nonnumber-type x) t))
                                  (atom (variable-nonnumber-type x)))
                             (format nil " ~A" (variable-nonnumber-type x)))
                            (t " nonnumber")))
                     ((variable-nonreal? x) " nonreal")
                     ((variable-noninteger? x) " noninteger")
                     (t "")))
       (when (variable-real? x)
         (cond ((and (variable-lower-bound x) (variable-upper-bound x))
                (format stream " ~D:~D"
                        (variable-lower-bound x) (variable-upper-bound x)))
               ((variable-lower-bound x)
                (format stream " ~D:" (variable-lower-bound x)))
               ((variable-upper-bound x)
                (format stream " :~D" (variable-upper-bound x)))))
       (when (and (variable-rational? x)
                  (variable-possibly-noninteger-rational? x)
                  (integerp (variable-max-denom x)))
         (format stream " max-denom:~D" (variable-max-denom x)))
       (when (and (not (eq (variable-enumerated-domain x) t))
                  (not (variable-boolean? x)))
         (format stream " enumerated-domain:~S"
                 (variable-enumerated-domain x)))
       (when (not (null (variable-enumerated-antidomain x)))
         (format stream " enumerated-antidomain:~S"
                 (variable-enumerated-antidomain x)))
       (format stream "]"))
      ((and x (or (consp x) (listp x) (vectorp x) (arrayp x) (hash-table-p x)))
       (format stream "[~S ~A:~A]" name (canonical-type x) x))
      (t (format stream "~S" x)))))

(defun variable-type? (x type)
;; X must be a variable.
 (and (not (eq (variable-nonnumber-type x) t))
      (atom (variable-nonnumber-type x))
      (eq (variable-nonnumber-type x) type)))

(defun variable-nontype? (x type)
;; X must be a variable.
 (and (not (eq (variable-nonnumber-type x) t))
      (atom (variable-nonnumber-type x))
      (not (eq (variable-nonnumber-type x) type))))

(defun variable-types? (x types)
;; X must be a variable.
 (and (listp (variable-nonnumber-type x))
      (equal types (variable-nonnumber-type x))))

(defun variable-nontypes? (x types)
;; X must be a variable.
 (and (listp (variable-nonnumber-type x))
      (not (equal (variable-nonnumber-type x) types))))

(defun variable-list? (x)
 (and (variable-possibly-nonboolean-nonnumber? x)
      (variable-type? x 'list)
      (not (variable-possibly-boolean? x))
      (not (variable-possibly-nonreal-number? x))
      (not (variable-possibly-noninteger-real? x))
      (not (variable-possibly-integer? x))
      (not (variable-possibly-noninteger-rational? x))))

;;; Restrictions

(defun restrict-integer! (x)
  ;; note: X must be a variable.
 (unless (variable-possibly-integer? x) (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-noninteger-rational? x)
          (local (setf (variable-possibly-noninteger-rational? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-real? x)
          (local (setf (variable-possibly-noninteger-real? x) nil))
          (setf run? t))
        (when (variable-possibly-nonreal-number? x)
          (local (setf (variable-possibly-nonreal-number? x) nil))
          (setf run? t))
        (when (variable-possibly-boolean? x)
          (local (setf (variable-possibly-boolean? x) nil))
          (setf run? t))
        (when (variable-possibly-nonboolean-nonnumber? x)
          (local (setf (variable-possibly-nonboolean-nonnumber? x) nil))
          (setf run? t))
        (when (and (variable-lower-bound x)
                   (not (integerp (variable-lower-bound x))))
          (if (and (variable-upper-bound x)
                   (< (variable-upper-bound x)
                      (ceiling (variable-lower-bound x))))
              (fail))
          (local (setf (variable-lower-bound x)
                       (ceiling (variable-lower-bound x))))
          (setf run? t))
        (when (and (variable-upper-bound x)
                   (not (integerp (variable-upper-bound x))))
          (if (and (variable-lower-bound x)
                   (> (variable-lower-bound x)
                      (floor (variable-upper-bound x))))
              (fail))
          (local (setf (variable-upper-bound x) (floor (variable-upper-bound x))))
          (setf run? t))
        (when (or (null (variable-max-denom x))
                  (and (integerp (variable-max-denom x))
                       (> (variable-max-denom x) 1)))
         (local (setf (variable-max-denom x) 1))
         (setf run? t))
        (when (variable-nonnumber-type x)
         (local (setf (variable-nonnumber-type x) nil)))
        (when run?
          (cond ((eq (variable-enumerated-domain x) t)
                 (if (and (variable-lower-bound x)
                          (variable-upper-bound x)
                          (or (null *maximum-discretization-range*)
                              (<= (- (variable-upper-bound x)
                                     (variable-lower-bound x))
                                  *maximum-discretization-range*)))
                     (set-enumerated-domain!
                      x (integers-between
                         (variable-lower-bound x)
                         (variable-upper-bound x)))))
                ((not (every #'integerp (variable-enumerated-domain x)))
                 (set-enumerated-domain!
                  x (remove-if-not #'integerp (variable-enumerated-domain x)))))
          (run-noticers x)))))

(defun restrict-noninteger! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-noninteger-rational? x)
              (variable-possibly-noninteger-real? x)
              (variable-possibly-nonreal-number? x)
              (variable-possibly-boolean? x)
              (variable-possibly-nonboolean-nonnumber? x))
     (fail))
  (when (and (or (eq (variable-value x) x) (not (variable? (variable-value x))))
             (variable-possibly-integer? x))
    (local (setf (variable-possibly-integer? x) nil))
    (if (and (not (eq (variable-enumerated-domain x) t))
             (some #'integerp (variable-enumerated-domain x)))
        (set-enumerated-domain!
         x (remove-if #'integerp (variable-enumerated-domain x))))
    (run-noticers x)))

(defun restrict-ratio! (x)
  ;; note: X must be a variable.
  (unless (variable-possibly-noninteger-rational? x) (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-integer? x)
          (local (setf (variable-possibly-integer? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-real? x)
          (local (setf (variable-possibly-noninteger-real? x) nil))
          (setf run? t))
        (when (variable-possibly-nonreal-number? x)
          (local (setf (variable-possibly-nonreal-number? x) nil))
          (setf run? t))
        (when (variable-possibly-boolean? x)
          (local (setf (variable-possibly-boolean? x) nil))
          (setf run? t))
        (when (variable-possibly-nonboolean-nonnumber? x)
          (local (setf (variable-possibly-nonboolean-nonnumber? x) nil))
          (setf run? t))
        (when (and (variable-lower-bound x)
                   (not (ratiop (variable-lower-bound x))))
           (let ((new-lower (if (variable-max-denom x)
                                (closest-ratio-lower (variable-lower-bound x) (variable-max-denom x))
                                (rationalize (variable-lower-bound x)))))
            (if (and (variable-upper-bound x)
                     (< (variable-upper-bound x) new-lower))
                (fail))
            (local (setf (variable-lower-bound x) new-lower))
         (setf run? t)))
        (when (and (variable-upper-bound x)
                   (not (ratiop (variable-upper-bound x))))
          (let ((new-upper (if (variable-max-denom x)
                              (closest-ratio-upper (variable-upper-bound x) (variable-max-denom x))
                              (rationalize (variable-upper-bound x)))))
            (if (and (variable-lower-bound x)
                    (> (variable-lower-bound x) new-upper))
                (fail))
            (local (setf (variable-upper-bound x) new-upper))
         (setf run? t)))
        (when (variable-nonnumber-type x)
         (local (setf (variable-nonnumber-type x) nil)))
        (when run?
          (cond
            ((eq (variable-enumerated-domain x) t)
            (let ((lb (variable-lower-bound x))
                  (ub (variable-upper-bound x)))
              (if (and lb ub (variable-max-denom x)
                         (<= (- ub lb) (safest-farey-range-size *maximum-discretization-range* (variable-max-denom x))))
                (set-enumerated-domain!
                  x (ratios-between lb ub (variable-max-denom x))))))
            ((not (every #'ratiop (variable-enumerated-domain x)))
             (if (variable-max-denom x)
                 (set-enumerated-domain!
                  x (remove-if-not (lambda (v) (and (ratiop v)
                                                    (<= (denominator v)
                                                        (variable-max-denom x))))
                    (variable-enumerated-domain x)))
                (set-enumerated-domain!
                  x (remove-if-not #'ratiop (variable-enumerated-domain x))))))
          (run-noticers x)))))

(defun restrict-nonratio! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-integer? x)
              (variable-possibly-noninteger-real? x)
              (variable-possibly-nonreal-number? x)
              (variable-possibly-boolean? x)
              (variable-possibly-nonboolean-nonnumber? x))
     (fail))
  (when (and (or (eq (variable-value x) x) (not (variable? (variable-value x))))
             (variable-possibly-noninteger-rational? x))
    (local (setf (variable-possibly-noninteger-rational? x) nil))
    (if (and (not (eq (variable-enumerated-domain x) t))
             (some #'ratiop (variable-enumerated-domain x)))
        (set-enumerated-domain!
         x (remove-if #'ratiop (variable-enumerated-domain x))))
    (run-noticers x)))

(defun restrict-rational! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-integer? x)
              (variable-possibly-noninteger-rational? x))
    (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-noninteger-real? x)
          (local (setf (variable-possibly-noninteger-real? x) nil))
          (setf run? t))
        (when (variable-possibly-boolean? x)
          (local (setf (variable-possibly-boolean? x) nil))
          (setf run? t))
        (when (variable-possibly-nonboolean-nonnumber? x)
          (local (setf (variable-possibly-nonboolean-nonnumber? x) nil))
          (setf run? t))
        (when (variable-possibly-nonreal-number? x)
          (local (setf (variable-possibly-nonreal-number? x) nil))
          (setf run? t))
        (when (and (variable-lower-bound x)
                   (not (rationalp (variable-lower-bound x))))
           (let ((new-lower (if (variable-max-denom x) 
                                (closest-rational-lower (variable-lower-bound x) (variable-max-denom x))
                                (rationalize (variable-lower-bound x)))))
            (if (and (variable-upper-bound x)
                     (< (variable-upper-bound x) new-lower))
                (fail))
            (local (setf (variable-lower-bound x) new-lower))
         (setf run? t)))
        (when (and (variable-upper-bound x)
                   (not (rationalp (variable-upper-bound x))))
          (let ((new-upper (if (variable-max-denom x)
                              (closest-rational-upper (variable-upper-bound x) (variable-max-denom x))
                              (rationalize (variable-upper-bound x)))))
            (if (and (variable-lower-bound x)
                    (> (variable-lower-bound x) new-upper))
                (fail))
            (local (setf (variable-upper-bound x) new-upper))
          (setf run? t)))
        (when (variable-nonnumber-type x)
         (local (setf (variable-nonnumber-type x) nil)))
        (when run?
          (cond
            ((eq (variable-enumerated-domain x) t)
             (if (and (variable-lower-bound x)
                      (variable-upper-bound x))
                 (cond ((variable-integer? x)
                         (when (or (null *maximum-discretization-range*)
                                 (<= (- (variable-upper-bound x)
                                        (variable-lower-bound x))
                                  *maximum-discretization-range*))
                             (set-enumerated-domain!
                              x (integers-between
                                (variable-lower-bound x)
                                (variable-upper-bound x)))))
                        ((and (variable-noninteger-rational? x)
                              (variable-max-denom x))
                        (when (<= (- (variable-upper-bound x) (variable-lower-bound x))
                                  (safest-farey-range-size *maximum-discretization-range* (variable-max-denom x)))       
                          (set-enumerated-domain!
                            x (ratios-between (variable-lower-bound x)
                                              (variable-upper-bound x)
                                              (variable-max-denom x)))))
                      ((and (variable-rational? x)
                            (variable-max-denom x))
                        (when (<= (- (variable-upper-bound x) (variable-lower-bound x))
                                  (safest-farey-range-size *maximum-discretization-range* (variable-max-denom x)))
                          (set-enumerated-domain!
                          x (rationals-between (variable-lower-bound x)
                                               (variable-upper-bound x)
                                               (variable-max-denom x))))))))
            ((not (every #'rationalp (variable-enumerated-domain x)))
             (if (variable-max-denom x)
                 (set-enumerated-domain!
                  x (remove-if-not (lambda (v) (or (integerp v)
                                                   (and (ratiop v)
                                                        (<= (denominator v)
                                                            (variable-max-denom x)))))
                    (variable-enumerated-domain x)))
                (set-enumerated-domain!
                  x (remove-if-not #'rationalp (variable-enumerated-domain x))))))
          (run-noticers x)))))

(defun restrict-nonrational! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-noninteger-real? x)
              (variable-possibly-nonreal-number? x)
              (variable-possibly-boolean? x)
              (variable-possibly-nonboolean-nonnumber? x))
    (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
    (when (variable-possibly-integer? x)
    (local (setf (variable-possibly-integer? x) nil))
    (setf run? t))
    (when (variable-possibly-noninteger-rational? x)
    (local (setf (variable-possibly-noninteger-rational? x) nil))
    (setf run? t))
    (when run?
    (if (and (not (eq (variable-enumerated-domain x) t))
             (some #'rationalp (variable-enumerated-domain x)))
        (set-enumerated-domain!
         x (remove-if #'rationalp (variable-enumerated-domain x))))
    (run-noticers x)))))

(defun restrict-float! (x)
(unless (variable-possibly-noninteger-real? x) (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-integer? x)
          (local (setf (variable-possibly-integer? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-rational? x)
          (local (setf (variable-possibly-noninteger-rational? x) nil))
          (setf run? t))
        (when (variable-possibly-nonreal-number? x)
          (local (setf (variable-possibly-nonreal-number? x) nil))
          (setf run? t))
        (when (variable-possibly-boolean? x)  
          (local (setf (variable-possibly-boolean? x) nil))
          (setf run? t))
        (when (variable-possibly-nonboolean-nonnumber? x)
          (local (setf (variable-possibly-nonboolean-nonnumber? x) nil))
          (setf run? t))
        (when (and (variable-lower-bound x)
              (not (floatp (variable-lower-bound x))))
          (local (setf (variable-lower-bound x)
                 (float (variable-lower-bound x))))
          (setf run? t))
        (when (and (variable-upper-bound x)
             (not (floatp (variable-upper-bound x))))
          (local (setf (variable-upper-bound x)
                 (float (variable-upper-bound x))))
          (setf run? t))
        (when (variable-nonnumber-type x)
         (local (setf (variable-nonnumber-type x) nil)))
        (when run?
          (if (and (not (eq (variable-enumerated-domain x) t))
                   (not (every #'floatp (variable-enumerated-domain x))))
              (set-enumerated-domain!
               x (remove-if-not #'floatp (variable-enumerated-domain x))))
          (run-noticers x)))))

(defun restrict-nonfloat! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-integer? x)
              (variable-possibly-noninteger-rational? x)
              (variable-possibly-nonreal-number? x)
              (variable-possibly-boolean? x)
              (variable-possibly-nonboolean-nonnumber? x))
    (fail))
  (when (and (or (eq (variable-value x) x) (not (variable? (variable-value x))))
              (variable-possibly-noninteger-real? x))
    (local (setf (variable-possibly-noninteger-real? x) nil))
    (if (and (not (eq (variable-enumerated-domain x) t))
              (some #'floatp (variable-enumerated-domain x)))
        (set-enumerated-domain!
          x (remove-if #'floatp (variable-enumerated-domain x))))
    (run-noticers x)))

(defun restrict-real! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-integer? x)
              (variable-possibly-noninteger-real? x)
              (variable-possibly-noninteger-rational? x))
    (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-nonreal-number? x)
          (local (setf (variable-possibly-nonreal-number? x) nil))
          (setf run? t))
        (when (variable-possibly-boolean? x)
          (local (setf (variable-possibly-boolean? x) nil))
          (setf run? t))
        (when (variable-possibly-nonboolean-nonnumber? x)
          (local (setf (variable-possibly-nonboolean-nonnumber? x) nil))
          (setf run? t))
        (when (variable-nonnumber-type x)
         (local (setf (variable-nonnumber-type x) nil)))
        (when run?
          (if (and (not (eq (variable-enumerated-domain x) t))
                   (not (every #'realp (variable-enumerated-domain x))))
              (set-enumerated-domain!
               x (remove-if-not #'realp (variable-enumerated-domain x))))
          (run-noticers x)))))

(defun restrict-nonreal! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-nonreal-number? x)
              (variable-possibly-boolean? x)
              (variable-possibly-nonboolean-nonnumber? x))
    (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-integer? x)
          (local (setf (variable-possibly-integer? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-rational? x)
          (local (setf (variable-possibly-noninteger-rational? x) nil))
          (setf run? t))  
        (when (variable-possibly-noninteger-real? x)
          (local (setf (variable-possibly-noninteger-real? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-rational? x)
          (local (setf (variable-possibly-noninteger-rational? x) nil))
          (setf run? t))
        (when run?
          (if (and (not (eq (variable-enumerated-domain x) t))
                   (some #'realp (variable-enumerated-domain x)))
              (set-enumerated-domain!
               x (remove-if #'realp (variable-enumerated-domain x))))
          (run-noticers x)))))

(defun restrict-number! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-integer? x)
              (variable-possibly-noninteger-real? x)
              (variable-possibly-nonreal-number? x)
              (variable-possibly-noninteger-rational? x))
    (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-boolean? x)
          (local (setf (variable-possibly-boolean? x) nil))
          (setf run? t))
        (when (variable-possibly-nonboolean-nonnumber? x)
          (local (setf (variable-possibly-nonboolean-nonnumber? x) nil))
          (setf run? t))
        (when (variable-nonnumber-type x)
         (local (setf (variable-nonnumber-type x) nil)))
        (when run?
          (if (and (not (eq (variable-enumerated-domain x) t))
                   (not (every #'numberp (variable-enumerated-domain x))))
              (set-enumerated-domain!
               x (remove-if-not #'numberp (variable-enumerated-domain x))))
          (run-noticers x)))))

(defun restrict-nonnumber! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-boolean? x)
              (variable-possibly-nonboolean-nonnumber? x))
    (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-integer? x)
          (local (setf (variable-possibly-integer? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-rational? x)
          (local (setf (variable-possibly-noninteger-rational? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-real? x)
          (local (setf (variable-possibly-noninteger-real? x) nil))
          (setf run? t))
        (when (variable-possibly-nonreal-number? x)
          (local (setf (variable-possibly-nonreal-number? x) nil))
          (setf run? t))
        (when run?
          (if (and (not (eq (variable-enumerated-domain x) t))
                   (some #'numberp (variable-enumerated-domain x)))
              (set-enumerated-domain!
               x (remove-if #'numberp (variable-enumerated-domain x))))
          (run-noticers x)))))

(defun restrict-boolean! (x)
  ;; note: X must be a variable.
  (unless (variable-possibly-boolean? x) (fail))
  (if (or (eq (variable-value x) x) (not (variable? (variable-value x))))
      (let ((run? nil))
        (when (variable-possibly-integer? x)
          (local (setf (variable-possibly-integer? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-rational? x)
          (local (setf (variable-possibly-noninteger-rational? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-real? x)
          (local (setf (variable-possibly-noninteger-real? x) nil))
          (setf run? t))
        (when (variable-possibly-nonreal-number? x)
          (local (setf (variable-possibly-nonreal-number? x) nil))
          (setf run? t))
        (when (variable-possibly-nonboolean-nonnumber? x)
          (local (setf (variable-possibly-nonboolean-nonnumber? x) nil))
          (setf run? t))
        (when (variable-possibly-noninteger-rational? x)
          (local (setf (variable-possibly-noninteger-rational? x) nil))
          (setf run? t))
        (when (not (eq (variable-nonnumber-type x) 'boolean))
           (local (setf (variable-nonnumber-type x) 'boolean))
           (setf run? t))
        (when run?
          (cond
            ((eq (variable-enumerated-domain x) t)
             (local
               (cond
                 ((member t (variable-enumerated-antidomain x) :test #'eq)
                  (cond ((member nil (variable-enumerated-antidomain x) :test #'eq)
                         (fail))
                        (t (setf (variable-enumerated-domain x) '(nil))
                           (setf (variable-enumerated-antidomain x) '())
                           (setf (variable-value x) nil))))
                 ((member nil (variable-enumerated-antidomain x) :test #'eq)
                  (setf (variable-enumerated-domain x) '(t))
                  (setf (variable-enumerated-antidomain x) '())
                  (setf (variable-value x) t))
                 (t (setf (variable-enumerated-domain x) '(t nil))
                    (unless (null (variable-enumerated-antidomain x))
                      (setf (variable-enumerated-antidomain x) '()))))))
            ((not (every #'booleanp (variable-enumerated-domain x)))
             (set-enumerated-domain!
              x (remove-if-not #'booleanp (variable-enumerated-domain x)))))
          (run-noticers x)))))

(defun restrict-nonboolean! (x)
  ;; note: X must be a variable.
  (unless (or (variable-possibly-integer? x)
              (variable-possibly-noninteger-real? x)
              (variable-possibly-nonreal-number? x)
              (variable-possibly-nonboolean-nonnumber? x)
              (variable-possibly-noninteger-rational? x))
    (fail))
  (when (and (or (eq (variable-value x) x) (not (variable? (variable-value x))))
             (variable-possibly-boolean? x))
    (local (setf (variable-possibly-boolean? x) nil))
    (when (variable-nonnumber-type x)
     (cond ((and (atom (variable-nonnumber-type x))
                 (eq (variable-nonnumber-type x) 'boolean))
            (fail))
          ((and (listp (variable-nonnumber-type x))
                (member 'boolean (variable-nonnumber-type x) :test #'eq))
           (local (setf (variable-nonnumber-type x)
                        (remove 'boolean (variable-nonnumber-type x) :test #'eq))))))
    (cond ((eq (variable-enumerated-domain x) t)
           (local (setf (variable-enumerated-antidomain x)
                        (adjoin t
                                (adjoin nil (variable-enumerated-antidomain x)
                                        :test #'eq)
                                :test #'eq))))
          ((some #'booleanp (variable-enumerated-domain x))
           (set-enumerated-domain!
            x (remove-if #'booleanp (variable-enumerated-domain x)))))
    (run-noticers x)))

(defun variable-possibly-type? (x type)
;; X must be a variable.
 (typecase (variable-nonnumber-type x)
  (boolean (variable-nonnumber-type x))
  (atom (typecase type
          (atom (eq (variable-nonnumber-type x) type))
          (list (member (variable-nonnumber-type x) type :test #'eq))))
  (list (typecase type
          (atom (member type (variable-nonnumber-type x) :test #'eq))
          (list (intersection (variable-nonnumber-type x) type :test #'eq))))
  (otherwise nil)))

(defun restrict-type! (x type)
;; X must be a variable.
  (unless (and (or (variable-possibly-boolean? x)
                   (variable-possibly-nonboolean-nonnumber? x))
               (variable-possibly-type? x type))
    (fail))
  (when (and (or (eq (variable-value x) x) (not (variable? (variable-value x))))
             (not (variable-type? x type)))
    (let ((run? nil))
      (when (variable-possibly-integer? x)
        (local (setf (variable-possibly-integer? x) nil))
        (setf run? t))
      (when (variable-possibly-noninteger-rational? x)
        (local (setf (variable-possibly-noninteger-rational? x) nil))
        (setf run? t))
      (when (variable-possibly-noninteger-real? x)
        (local (setf (variable-possibly-noninteger-real? x) nil))
        (setf run? t))
      (when (variable-possibly-nonreal-number? x)
        (local (setf (variable-possibly-nonreal-number? x) nil))
        (setf run? t))
      (when (variable-possibly-boolean? x)
        (unless (or (eq type 'boolean)
                    (and (listp (variable-nonnumber-type x))
                         (member 'boolean (variable-nonnumber-type x) :test #'eq)))
        (local (setf (variable-possibly-boolean? x) nil))
        (setf run? t)))
      (when (eq (variable-nonnumber-type x) t)
        (local (setf (variable-nonnumber-type x) type))
        (setf run? t))
      (when (listp (variable-nonnumber-type x))
       (if (not (member type (variable-nonnumber-type x) :test #'eq))
           (fail))
        (local (setf (variable-nonnumber-type x) type))
        (setf run? t))
      (when run?
        (when (and (not (eq (variable-enumerated-domain x) t))
                    (some (lambda (v) (not (eq (canonical-type v) type))) (variable-enumerated-domain x)))
          (set-enumerated-domain!
            x (remove-if-not (lambda (v) (eq (canonical-type v) type)) (variable-enumerated-domain x))))
    (run-noticers x)))))

(defun restrict-nontype! (x type)
;; X must be a variable.
  (unless (and (or (variable-possibly-boolean? x)
                   (variable-possibly-nonboolean-nonnumber? x))
               (variable-nontype? x type))
    (fail))
  (when (and (variable-possibly-type? x type)
             (or (eq (variable-value x) x) (not (variable? (variable-value x)))))
   (let ((run? nil))
    (when (eq type 'boolean)
     (unless (member 'boolean (variable-nonnumber-type x) :test #'eq)
      (local (setf (variable-possibly-boolean? x) nil))
      (setf run? t)))
    (when (listp (variable-nonnumber-type x))
       (local (setf (variable-nonnumber-type x)
                    (remove type (variable-nonnumber-type x) :test #'eq)))
       (setf run? t))
    (when (null (variable-nonnumber-type x))
     (fail))
    (when run? 
      (if (and (not (eq (variable-enumerated-domain x) t))
               (some (lambda (v)
                       (eq (canonical-type v) type))
               (variable-enumerated-domain x)))
           (set-enumerated-domain!
            x (remove-if (lambda (v)
                          (eq (canonical-type v) type))
           (variable-enumerated-domain x))))
    (run-noticers x)))))

(defun restrict-types! (x types)
;; X must be a variable.
  (unless (and (listp types)
               (or (variable-possibly-boolean? x)
                   (variable-possibly-nonboolean-nonnumber? x))
               (variable-possibly-type? x types))
    (fail))
  (when (and (not (variable-types? x types))
             (or (eq (variable-value x) x) (not (variable? (variable-value x)))))
    (let ((run? nil))
      (when (variable-possibly-integer? x)
        (local (setf (variable-possibly-integer? x) nil))
        (setf run? t))
      (when (variable-possibly-noninteger-rational? x)
        (local (setf (variable-possibly-noninteger-rational? x) nil))
        (setf run? t))
      (when (variable-possibly-noninteger-real? x)
        (local (setf (variable-possibly-noninteger-real? x) nil))
        (setf run? t))
      (when (variable-possibly-nonreal-number? x)
        (local (setf (variable-possibly-nonreal-number? x) nil))
        (setf run? t))
      (when (variable-possibly-boolean? x)
        (unless (member 'boolean (variable-nonnumber-type x) :test #'eq)
        (local (setf (variable-possibly-boolean? x) nil))
        (setf run? t))) 
      (when (eq (variable-nonnumber-type x) t)
       (local (setf (variable-nonnumber-type x) types))
       (setf run? t))
      (when (listp (variable-nonnumber-type x))
       (let ((intersection (intersection (variable-nonnumber-type x) types :test #'eq)))
         (if intersection
             (local (setf (variable-nonnumber-type x) intersection))
             (fail))
         (setf run? t)))
    (when run?
      (if (and (not (eq (variable-enumerated-domain x) t))
               (some (lambda (v) (not (member (canonical-type v) types :test #'eq))) (variable-enumerated-domain x)))
      (set-enumerated-domain!
        x (remove-if-not (lambda (v) (member (canonical-type v) types :test #'eq)) (variable-enumerated-domain x))))
    (run-noticers x)))))

(defun restrict-nontypes! (x types)
;; X must be a variable.
  (unless (and (listp types)
               (or (variable-possibly-boolean? x)
                   (variable-possibly-nonboolean-nonnumber? x))
               (variable-nontypes? x types))
    (fail))
  (when (and (variable-possibly-type? x types)
             (or (eq (variable-value x) x) (not (variable? (variable-value x)))))
   (let ((run? nil))
    (when (member 'boolean types :test #'eq)
     (local (setf (variable-possibly-boolean? x) nil))
     (setf run? t))
    (when (and (listp (variable-nonnumber-type x))
               (some (lambda (type)
                       (member type (variable-nonnumber-type x) :test #'eq))
                      types))
       (local (setf (variable-nonnumber-type x)
                    (set-difference (variable-nonnumber-type x) types :test #'eq)))
       (setf run? t))
    (when (null (variable-nonnumber-type x))
     (fail))
    (when run? 
      (if (and (not (eq (variable-enumerated-domain x) t))
               (some (lambda (v)
                       (member (canonical-type v) types :test #'eq))
               (variable-enumerated-domain x)))
           (set-enumerated-domain!
            x (remove-if (lambda (v)
                          (member (canonical-type v) types :test #'eq))
           (variable-enumerated-domain x))))
    (run-noticers x)))))

(defun prune-enumerated-domain (x &optional (enumerated-domain (variable-enumerated-domain x)))
  ;; Returns an enumerated domain from which elements what violate
  ;; restrictions on X have been removed.
  (declare (optimize (speed 3) (space 3)))
  (remove-if-not (lambda (elt)
                   (cond ((numberp elt)
                          (if (realp elt)
                              (when (cond ((integerp elt)
                                           (variable-possibly-integer? x))
                                           ((ratiop elt)
                                            (and (variable-possibly-noninteger-rational? x)
                                                  (or (not (variable-max-denom x))
                                                      (<= (denominator elt) (variable-max-denom x)))))
                                          (t
                                           (variable-possibly-noninteger-real? x)))
                                (let ((low (variable-lower-bound x))
                                      (high (variable-upper-bound x)))
                                  (cond ((and low high)
                                         (<= low elt high))
                                        (low
                                         (<= low elt))
                                        (high
                                         (<= elt high))
                                        (t t))))
                              (variable-possibly-nonreal-number? x)))
                         ((booleanp elt)
                          (and (variable-possibly-boolean? x)
                               (variable-possibly-type? x 'boolean)))
                         (t
                           (and (variable-possibly-nonboolean-nonnumber? x)
                                (variable-possibly-type? x (canonical-type elt))))))
                 enumerated-domain))

(defun share! (x y)
  ;; note: X and Y must be variables such that (EQ X (VALUE-OF X)) and
  ;;       (EQ Y (VALUE-OF Y)).
  (declare (optimize (speed 3) (space 3)))
  (let ((run? nil)
        (y-lower-bound? nil)
        (y-upper-bound? nil)
        (x-lower-bound (variable-lower-bound x))
        (x-upper-bound (variable-upper-bound x))
        (y-lower-bound (variable-lower-bound y))
        (y-upper-bound (variable-upper-bound y)))
    ;; Apply all restrictions from X to Y.
(cond
 ;; If y is integer and x is not integer, prune x's bounds to integers
 ((and (variable-integer? y) (not (variable-integer? x)))
  (when x-lower-bound
    (setf x-lower-bound (ceiling x-lower-bound)))
  (when x-upper-bound
    (setf x-upper-bound (floor x-upper-bound))))
 ;; If y is noninteger-rational and x is nonratio, prune x's bounds to ratios
 ((and (variable-noninteger-rational? y) (variable-nonratio? x))
  (cond
    ((null (variable-max-denom x))
     (when x-lower-bound
       (setf x-lower-bound (rationalize x-lower-bound)))
     (when x-upper-bound
       (setf x-upper-bound (rationalize x-upper-bound))))
    ((variable-max-denom x)
     (when x-lower-bound
       (setf x-lower-bound (closest-ratio-lower x-lower-bound (variable-max-denom x))))
     (when x-upper-bound
       (setf x-upper-bound (closest-ratio-upper x-upper-bound (variable-max-denom x)))))))
 ;; If y is rational and x is nonrational, prune x's bounds to rationals
 ((and (variable-rational? y) (variable-nonrational? x))
  (cond
    ((null (variable-max-denom x))
     (when x-lower-bound
       (setf x-lower-bound (rationalize x-lower-bound)))
     (when x-upper-bound
       (setf x-upper-bound (rationalize x-upper-bound))))
    ((variable-max-denom x)
     (when x-lower-bound
       (setf x-lower-bound (closest-rational-lower x-lower-bound (variable-max-denom x))))
     (when x-upper-bound
       (setf x-upper-bound (closest-rational-upper x-upper-bound (variable-max-denom x)))))))
 ;; If y is not integer and x is integer, prune y's bounds to integers
 ((and (not (variable-integer? y)) (variable-integer? x))
  (when (and y-lower-bound (not (integerp y-lower-bound)))
    (setf y-lower-bound (ceiling y-lower-bound))
    (setf y-lower-bound? t))
  (when (and y-upper-bound (not (integerp y-upper-bound)))
    (setf y-upper-bound (floor y-upper-bound))
    (setf y-upper-bound? t)))
 ;; If y is nonratio and x is noninteger-rational, prune y's bounds to ratios
 ((and (variable-nonratio? y) (variable-noninteger-rational? x))
  (cond
    ((null (variable-max-denom x))
     (when y-lower-bound
       (setf y-lower-bound (rationalize y-lower-bound))
       (setf y-lower-bound? t))
     (when y-upper-bound
       (setf y-upper-bound (rationalize y-upper-bound))
       (setf y-upper-bound? t)))
    ((variable-max-denom x)
     (when y-lower-bound
       (setf y-lower-bound (closest-ratio-lower y-lower-bound (variable-max-denom x)))
       (setf y-lower-bound? t))
     (when y-upper-bound
       (setf y-upper-bound (closest-ratio-upper y-upper-bound (variable-max-denom x)))
       (setf y-upper-bound? t)))))
 ;; If y is nonrational and x is rational, prune y's bounds to rationals
 ((and (variable-nonrational? y) (variable-rational? x))
  (cond
    ((null (variable-max-denom x))
     (when y-lower-bound
       (setf y-lower-bound (rationalize y-lower-bound))
       (setf y-lower-bound? t))
     (when y-upper-bound
       (setf y-upper-bound (rationalize y-upper-bound))
       (setf y-upper-bound? t)))
    ((variable-max-denom x)
     (when y-lower-bound
       (setf y-lower-bound (closest-rational-lower y-lower-bound (variable-max-denom x)))
       (setf y-lower-bound? t))
     (when y-upper-bound
       (setf y-upper-bound (closest-rational-upper y-upper-bound (variable-max-denom x)))
       (setf y-upper-bound? t)))))
 ;; If both x and y are rational, use the minimum max-denom for both
 ((and (variable-rational? x) (variable-rational? y))
  (let ((min-denom (cond ((variable-max-denom x)
                           (if (variable-max-denom y)
                               (min (variable-max-denom x) (variable-max-denom y))
                               (variable-max-denom x)))
                          ((variable-max-denom y) (variable-max-denom y)))))
    (when min-denom
      (when x-lower-bound
        (setf x-lower-bound (closest-rational-lower x-lower-bound min-denom)))
      (when x-upper-bound
        (setf x-upper-bound (closest-rational-upper x-upper-bound min-denom)))
      (when y-lower-bound
        (setf y-lower-bound (closest-rational-lower y-lower-bound min-denom))
        (setf y-lower-bound? t))
      (when y-upper-bound
        (setf y-upper-bound (closest-rational-upper y-upper-bound min-denom))
        (setf y-upper-bound? t))
      (local (setf (variable-max-denom x) min-denom))
      (local (setf (variable-max-denom y) min-denom)))))
   ;; Share nonnumber-type slots between x and y
  ((and (variable-nonnumber-type x)
        (not (eq (variable-nonnumber-type x) t)))
        ;; If both x and y have nonnumber types, synchronize them
    (if (and (variable-nonnumber-type y)
             (not (eq (variable-nonnumber-type y) t)))
        (let* ((x-types (if (atom (variable-nonnumber-type x))
                           (list (variable-nonnumber-type x))
                           (variable-nonnumber-type x)))
              (y-types (if (atom (variable-nonnumber-type y))
                           (list (variable-nonnumber-type y))
                           (variable-nonnumber-type y)))
              (shared-types (intersection x-types y-types :test #'eq)))
            (unless shared-types (fail))
            (unless (equal shared-types y-types)
              (local (setf (variable-nonnumber-type y)
                           (if (= (length shared-types) 1)
                               (first shared-types)
                               shared-types)))
              (setf run? t)))
         ;; If only x have a nonnumber-type, prune y types with x types
         (local (setf (variable-nonnumber-type y) (variable-nonnumber-type x)))))
  ;; If only Y have nonnumber types, prune x types with y types
  ((and (variable-nonnumber-type y)
        (not (eq (variable-nonnumber-type y) t)))
   (local (setf (variable-nonnumber-type x) (variable-nonnumber-type y)))
   (setf run? t)))
    (when (and (not (variable-possibly-integer? x))
               (variable-possibly-integer? y))
      (local (setf (variable-possibly-integer? y) nil))
      (setf run? t))
    (when (and (not (variable-possibly-noninteger-rational? x))
               (variable-possibly-noninteger-rational? y))
      (local (setf (variable-possibly-noninteger-rational? y) nil))
      (setf run? t))
    (when (and (not (variable-possibly-noninteger-real? x))
               (variable-possibly-noninteger-real? y))
      (local (setf (variable-possibly-noninteger-real? y) nil))
      (setf run? t))
    (when (and (not (variable-possibly-nonreal-number? x))
               (variable-possibly-nonreal-number? y))
      (local (setf (variable-possibly-nonreal-number? y) nil))
      (setf run? t))
    (when (and (not (variable-possibly-boolean? x))
               (variable-possibly-boolean? y))
      (local (setf (variable-possibly-boolean? y) nil))
      (setf run? t))
    (when (and (not (variable-possibly-nonboolean-nonnumber? x))
               (variable-possibly-nonboolean-nonnumber? y))
      (local (setf (variable-possibly-nonboolean-nonnumber? y) nil))
      (setf run? t))
    (unless (or (variable-possibly-integer? y)
                (variable-possibly-noninteger-rational? y)
                (variable-possibly-noninteger-real? y)
                (variable-possibly-nonreal-number? y)
                (variable-possibly-boolean? y)
                (variable-possibly-nonboolean-nonnumber? y))
      (fail))
    (cond ((and x-lower-bound
                (or (not y-lower-bound) (> x-lower-bound y-lower-bound)))
           (local (setf (variable-lower-bound y) x-lower-bound))
           (setf run? t))
          (y-lower-bound?
           (local (setf (variable-lower-bound y) y-lower-bound))
           (setf run? t)))
    (cond ((and x-upper-bound
                (or (not y-upper-bound) (< x-upper-bound y-upper-bound)))
           (local (setf (variable-upper-bound y) x-upper-bound))
           (setf run? t))
          (y-upper-bound?
           (local (setf (variable-upper-bound y) y-upper-bound))
           (setf run? t)))
    (unless (or (null (variable-lower-bound y))
                (null (variable-upper-bound y))
                (< (variable-lower-bound y) (variable-upper-bound y)))
      (fail))
    (when run?
      ;; Something has changed: update enumerated domain of Y.    
      (let ((lower-bound (variable-lower-bound y))
        (upper-bound (variable-upper-bound y)))
      (if (eq (variable-enumerated-domain y) t)
          (cond
            ((and lower-bound
              upper-bound
              (variable-integer? y))
              (if (or (null *maximum-discretization-range*)
                (<= (- upper-bound lower-bound)
                  *maximum-discretization-range*))
            (set-enumerated-domain!
            y (integers-between lower-bound upper-bound))))
            ((and lower-bound
              upper-bound
              (variable-noninteger-rational? y)
              (and (variable-max-denom y)
                   (<= (- upper-bound lower-bound)
                       (safest-farey-range-size *maximum-discretization-range* (variable-max-denom y)))))
            (set-enumerated-domain!
            y (ratios-between lower-bound upper-bound (variable-max-denom y))))
            ((and lower-bound
              upper-bound
              (variable-rational? y)
              (and (variable-max-denom y)
                   (<= (- upper-bound lower-bound)
                       (safest-farey-range-size *maximum-discretization-range* (variable-max-denom y)))))
            (set-enumerated-domain!
            y (rationals-between lower-bound upper-bound (variable-max-denom y)))))
            (set-enumerated-domain!
            y (prune-enumerated-domain y (variable-enumerated-domain y))))))
          (local (let* ((enumerated-domain
                         (cond
                           ((eq (variable-enumerated-domain x) t)
                            (if (eq (variable-enumerated-domain y) t)
                                t
                                (set-difference (variable-enumerated-domain y)
                                                (variable-enumerated-antidomain x)
                                                :test #'generic-equal)))
                           ((eq (variable-enumerated-domain y) t)
                            (set-difference (variable-enumerated-domain x)
                                            (variable-enumerated-antidomain y)
                                            :test #'generic-equal))
                           (t (intersection (variable-enumerated-domain x)
                                            (variable-enumerated-domain y)
                                            :test #'generic-equal))))
                        (enumerated-antidomain
                         (if (eq enumerated-domain t)
                             (union (variable-enumerated-antidomain x)
                                    (variable-enumerated-antidomain y)
                                    :test #'generic-equal)
                             '())))
                 (if (null enumerated-domain) (fail))
                 (if (and (not (eq enumerated-domain t))
                          (or (eq (variable-enumerated-domain y) t)
                              (< (length enumerated-domain)
                                 (length (variable-enumerated-domain y)))))
                     (set-enumerated-domain!
                      y (prune-enumerated-domain y enumerated-domain)))
                 (if (if (eq enumerated-domain t)
                         (> (length enumerated-antidomain)
                            (length (variable-enumerated-antidomain y)))
                         (not (null (variable-enumerated-antidomain y))))
                     (setf (variable-enumerated-antidomain y) enumerated-antidomain)))
      (setf (variable-noticers y)
            (append (variable-noticers y) (variable-noticers x)))
      (setf (variable-noticers x) '())
      (setf (variable-value x) y)))
    (run-noticers y))

(defun restrict-value! (x value)
  ;; note: X must be a variable such that (EQ X (VALUE-OF X)).
  ;; note: VALUE must not be a variable.
  (if (occurs-in? x value) (fail))
  (typecase value
    (integer (unless (variable-possibly-integer? x) (fail)))
    (ratio (unless (variable-possibly-noninteger-rational? x) (fail)))
    (float (unless (variable-possibly-noninteger-real? x) (fail)))
    (number (unless (variable-possibly-nonreal-number? x) (fail)))
    (boolean (unless (variable-possibly-boolean? x) (fail)))
    (otherwise (unless (variable-possibly-nonboolean-nonnumber? x) (fail))))
  ;; needs work: This is sound only if VALUE does not contain any variables.
  (if (eq (variable-enumerated-domain x) t)
      (if (member value (variable-enumerated-antidomain x) :test #'generic-equal)
          (fail))
      (unless (member value (variable-enumerated-domain x) :test #'generic-equal)
        (fail)))
  (if (and (realp value)
           (or (and (variable-lower-bound x)
                    (< value (variable-lower-bound x)))
               (and (variable-upper-bound x)
                    (> value (variable-upper-bound x)))))
      (fail))
  (if (and (ratiop value)
           (variable-max-denom x) 
           (> (denominator value) (variable-max-denom x)))
      (fail))
  (if (or (variable-possibly-boolean? x)
          (variable-possibly-nonboolean-nonnumber? x))
      (unless (variable-possibly-type? x (canonical-type value))
       (fail)))
  (local (setf (variable-value x) value)
         (typecase value
           (integer (if (variable-possibly-noninteger-rational? x)
                        (setf (variable-possibly-noninteger-rational? x) nil))
                    (if (variable-possibly-noninteger-real? x)
                        (setf (variable-possibly-noninteger-real? x) nil))                        
                    (if (variable-possibly-nonreal-number? x)
                        (setf (variable-possibly-nonreal-number? x) nil))
                    (if (variable-possibly-boolean? x)
                        (setf (variable-possibly-boolean? x) nil))
                    (if (variable-possibly-nonboolean-nonnumber? x)
                        (setf (variable-possibly-nonboolean-nonnumber? x) nil))
                    (if (or (null (variable-lower-bound x))
                            (not (integerp (variable-lower-bound x)))
                            (> value (variable-lower-bound x)))
                        (setf (variable-lower-bound x) value))
                    (if (or (null (variable-upper-bound x))
                            (not (integerp (variable-upper-bound x)))
                            (< value (variable-upper-bound x)))
                        (setf (variable-upper-bound x) value))
                    (if (or (null (variable-max-denom x))
                            (> (variable-max-denom x) 1))
                        (setf (variable-max-denom x) 1))
                    (if (variable-nonnumber-type x)
                        (local (setf (variable-nonnumber-type x) nil))))
            (ratio
                     (if (variable-possibly-integer? x)
                       (setf (variable-possibly-integer? x) nil))
                     (if (variable-possibly-noninteger-real? x)
                        (setf (variable-possibly-noninteger-real? x) nil))  
                     (if (variable-possibly-nonreal-number? x)
                       (setf (variable-possibly-nonreal-number? x) nil))
                     (if (variable-possibly-boolean? x)
                       (setf (variable-possibly-boolean? x) nil))
                     (if (variable-possibly-nonboolean-nonnumber? x)
                       (setf (variable-possibly-nonboolean-nonnumber? x) nil))
                     (if (or (null (variable-lower-bound x))
                         (> value (variable-lower-bound x)))
                       (setf (variable-lower-bound x) value))
                     (if (or (null (variable-upper-bound x))
                         (< value (variable-upper-bound x)))
                       (setf (variable-upper-bound x) value))
                      (if (or (null (variable-max-denom x))
                              (< (denominator value) (variable-max-denom x)))
                       (setf (variable-max-denom x) (denominator value)))
                    (if (variable-nonnumber-type x)
                        (local (setf (variable-nonnumber-type x) nil))))
           (float (if (variable-possibly-integer? x)
                     (setf (variable-possibly-integer? x) nil))
                  (if (variable-possibly-noninteger-rational? x)
                      (setf (variable-possibly-noninteger-rational? x) nil))
                  (if (variable-possibly-nonreal-number? x)
                      (setf (variable-possibly-nonreal-number? x) nil))
                  (if (variable-possibly-boolean? x)
                      (setf (variable-possibly-boolean? x) nil))
                  (if (variable-possibly-nonboolean-nonnumber? x)
                      (setf (variable-possibly-nonboolean-nonnumber? x) nil))
                  (if (or (null (variable-lower-bound x))
                          (> value (variable-lower-bound x)))
                      (setf (variable-lower-bound x) value))
                  (if (or (null (variable-upper-bound x))
                          (< value (variable-upper-bound x)))
                      (setf (variable-upper-bound x) value))
                  (if (variable-max-denom x)
                     (setf (variable-max-denom x) nil))
                  (if (variable-nonnumber-type x)
                      (local (setf (variable-nonnumber-type x) nil))))
           (number (if (variable-possibly-integer? x)
                       (setf (variable-possibly-integer? x) nil))
                   (if (variable-possibly-noninteger-rational? x)
                        (setf (variable-possibly-noninteger-rational? x) nil))    
                   (if (variable-possibly-noninteger-real? x)
                       (setf (variable-possibly-noninteger-real? x) nil))
                   (if (variable-possibly-boolean? x)
                       (setf (variable-possibly-boolean? x) nil))
                   (if (variable-possibly-nonboolean-nonnumber? x)
                       (setf (variable-possibly-nonboolean-nonnumber? x) nil))
                   (if (variable-max-denom x)
                       (setf (variable-max-denom x) nil))
                   (if (variable-nonnumber-type x)
                       (local (setf (variable-nonnumber-type x) nil))))
           (boolean (if (variable-possibly-integer? x)
                        (setf (variable-possibly-integer? x) nil))
                    (if (variable-possibly-noninteger-real? x)
                        (setf (variable-possibly-noninteger-real? x) nil))
                    (if (variable-possibly-nonreal-number? x)
                        (setf (variable-possibly-nonreal-number? x) nil))
                    (if (variable-possibly-nonboolean-nonnumber? x)
                        (setf (variable-possibly-nonboolean-nonnumber? x) nil))
                    (if (variable-max-denom x)
                        (setf (variable-max-denom x) nil))
                    (if (not (eq (variable-nonnumber-type x) 'boolean))
                        (setf (variable-nonnumber-type x) 'boolean)))
           (otherwise (if (variable-possibly-integer? x)
                          (setf (variable-possibly-integer? x) nil))
                      (if (variable-possibly-noninteger-rational? x)
                        (setf (variable-possibly-noninteger-rational? x) nil))
                      (if (variable-possibly-noninteger-real? x)
                          (setf (variable-possibly-noninteger-real? x) nil))
                      (if (variable-possibly-nonreal-number? x)
                          (setf (variable-possibly-nonreal-number? x) nil))
                      (if (variable-possibly-boolean? x)
                          (setf (variable-possibly-boolean? x) nil))
                      (if (variable-max-denom x)
                          (setf (variable-max-denom x) nil)))
                      (if (not (eq (variable-nonnumber-type x) (canonical-type value))
                          (setf (variable-nonnumber-type x) (canonical-type value)))))
         (cond ((eq (variable-enumerated-domain x) t)
                ;; needs work: This is sound only if VALUE does not contain any
                ;;             variables.
                (setf (variable-enumerated-domain x) (list value))
                (setf (variable-enumerated-antidomain x) '()))
               ((not (null (rest (variable-enumerated-domain x))))
                ;; needs work: This is sound only if VALUE does not contain any
                ;;             variables.
                (setf (variable-enumerated-domain x) (list value)))))
  (run-noticers x))

(defun restrict-true! (x)
  ;; note: X must be a Boolean variable.
  (if (eq (variable-value x) nil) (fail))
  (when (eq (variable-value x) x)
    (local (setf (variable-value x) t)
           (setf (variable-enumerated-domain x) '(t)))
    (run-noticers x)))

(defun restrict-false! (x)
  ;; note: X must be a Boolean variable.
  (if (eq (variable-value x) t) (fail))
  (when (eq (variable-value x) x)
    (local (setf (variable-value x) nil)
           (setf (variable-enumerated-domain x) '(nil)))
    (run-noticers x)))

(defun set-enumerated-domain! (x enumerated-domain)
  ;; note: X must be a variable such that (EQ X (VALUE-OF X)).
  ;; note: All callers must insure that the new ENUMERATED-DOMAIN is a subset
  ;;       of the old one.
  (if (null enumerated-domain) (fail))
  (local
    (cond
      ((eq (variable-enumerated-domain x) t)
       (setf (variable-enumerated-domain x) enumerated-domain)
       (unless (null (variable-enumerated-antidomain x))
         (setf (variable-enumerated-antidomain x) '()))
       (if (and (variable-possibly-boolean? x)
                (not (some #'booleanp enumerated-domain)))
           (setf (variable-possibly-boolean? x) nil))
       (if (and (variable-possibly-nonboolean-nonnumber? x)
                (not (some #'(lambda (x)
                               (and (not (booleanp x)) (not (numberp x))))
                           enumerated-domain)))
           (setf (variable-possibly-nonboolean-nonnumber? x) nil))
       (if (and (variable-possibly-nonreal-number? x)
                (not (some #'(lambda (x) (and (not (realp x)) (numberp x)))
                           enumerated-domain)))
           (setf (variable-possibly-nonreal-number? x) nil))
       (if (and (variable-possibly-noninteger-real? x)
                (not (some #'floatp  enumerated-domain)))
          (setf (variable-possibly-noninteger-real? x) nil))
      (if (and (variable-possibly-noninteger-rational? x)
               (not (some #'ratiop enumerated-domain)))
          (setf (variable-possibly-noninteger-rational? x) nil))
       (if (and (variable-possibly-integer? x)
                (not (some #'integerp enumerated-domain)))
           (setf (variable-possibly-integer? x) nil))
       (if (variable-real? x)
           (let ((lower-bound (reduce #'min enumerated-domain))
                 (upper-bound (reduce #'max enumerated-domain)))
             (if (or (null (variable-lower-bound x))
                     (> lower-bound (variable-lower-bound x)))
                 (setf (variable-lower-bound x) lower-bound))
             (if (or (null (variable-upper-bound x))
                     (< upper-bound (variable-upper-bound x)))
                 (setf (variable-upper-bound x) upper-bound))))
      (if (and (or (variable-possibly-noninteger-rational? x)
                   (variable-possibly-integer? x))
               (some #'rationalp enumerated-domain))
         (let ((max-denom-in-domain
                (reduce #'max
                        (remove-if-not #'rationalp enumerated-domain)
                        :key #'denominator)))
           (setf (variable-max-denom x) max-denom-in-domain)))
       (if (null (rest enumerated-domain))
           (setf (variable-value x) (first enumerated-domain)))
     (if (or (variable-possibly-boolean? x)
             (variable-possibly-nonboolean-nonnumber? x))
         (let* ((types (remove-duplicates (mapcar #'canonical-type enumerated-domain) :test #'eq))
                (new-nonnumber-type (if (= (length types) 1) (first types) types)))
          (if (not (eq (variable-nonnumber-type x) t))
              (unless (equal (variable-nonnumber-type x) new-nonnumber-type)
                (setf (variable-nonnumber-type x) new-nonnumber-type))
              (setf (variable-nonnumber-type x) new-nonnumber-type))))
     (if (null (rest enumerated-domain))
         (setf (variable-value x) (first enumerated-domain)))
       t)
      ((< (length enumerated-domain) (length (variable-enumerated-domain x)))
       (setf (variable-enumerated-domain x) enumerated-domain)
       (if (and (variable-possibly-boolean? x)
                (not (some #'booleanp enumerated-domain)))
           (setf (variable-possibly-boolean? x) nil))
       (if (and (variable-possibly-nonboolean-nonnumber? x)
                (not (some #'(lambda (x)
                               (and (not (booleanp x)) (not (numberp x))))
                           enumerated-domain)))
           (setf (variable-possibly-nonboolean-nonnumber? x) nil))
       (if (and (variable-possibly-nonreal-number? x)
                (not (some #'(lambda (x) (and (not (realp x)) (numberp x)))
                           enumerated-domain)))
           (setf (variable-possibly-nonreal-number? x) nil))
       (if (and (variable-possibly-noninteger-real? x)
                (not (some #'floatp enumerated-domain)))
           (setf (variable-possibly-noninteger-real? x) nil))
      (if (and (variable-possibly-noninteger-rational? x)
               (not (some #'ratiop enumerated-domain)))
          (setf (variable-possibly-noninteger-rational? x) nil))
       (if (and (variable-possibly-integer? x)
                (not (some #'integerp enumerated-domain)))
           (setf (variable-possibly-integer? x) nil))
       (if (variable-real? x)
           (let ((lower-bound (reduce #'min enumerated-domain))
                 (upper-bound (reduce #'max enumerated-domain)))
             (if (or (null (variable-lower-bound x))
                     (> lower-bound (variable-lower-bound x)))
                 (setf (variable-lower-bound x) lower-bound))
             (if (or (null (variable-upper-bound x))
                     (< upper-bound (variable-upper-bound x)))
                 (setf (variable-upper-bound x) upper-bound))))
      (if (and (or (variable-possibly-noninteger-rational? x)
                   (variable-possibly-integer? x))
               (some #'rationalp enumerated-domain))
         (let ((max-denom-in-domain
                (reduce #'max
                        (remove-if-not #'rationalp enumerated-domain)
                        :key #'denominator)))
           (setf (variable-max-denom x) max-denom-in-domain)))
     (if (or (variable-possibly-boolean? x)
             (variable-possibly-nonboolean-nonnumber? x))
         (let* ((types (remove-duplicates (mapcar #'canonical-type enumerated-domain) :test #'eq))
                (new-nonnumber-type (if (= (length types) 1) (first types) types)))
          (if (not (eq (variable-nonnumber-type x) t))
              (unless (equal (variable-nonnumber-type x) new-nonnumber-type)
                (setf (variable-nonnumber-type x) new-nonnumber-type))
              (setf (variable-nonnumber-type x) new-nonnumber-type))))
     (if (null (rest enumerated-domain))
         (setf (variable-value x) (first enumerated-domain)))
       t)
      (t nil))))

(defun restrict-enumerated-domain! (x enumerated-domain)
  ;; note: X must be a variable such that (EQ X (VALUE-OF X)).
  ;; note: ENUMERATED-DOMAIN must not be a variable.
  (unless (typep enumerated-domain 'sequence) (fail))
  (when (every #'ground? enumerated-domain)
  (setf enumerated-domain
          (remove-duplicates (map 'list #'eliminate-variables enumerated-domain)
                             :test #'generic-equal))
    (unless (variable-possibly-boolean? x)
      (setf enumerated-domain (remove-if #'booleanp enumerated-domain)))
    (unless (variable-possibly-nonboolean-nonnumber? x)
      (setf enumerated-domain
            (remove-if #'(lambda (x) (and (not (booleanp x)) (not (numberp x))))
                       enumerated-domain)))
    (when (and (not (eq (variable-nonnumber-type x) t))
               (or (variable-possibly-boolean? x)
                   (variable-possibly-nonboolean-nonnumber? x)))
      (setf enumerated-domain
            (let ((allowed-types (if (atom (variable-nonnumber-type x))
                                     (list (variable-nonnumber-type x))
                                     (variable-nonnumber-type x))))
              (format nil "Restricting enumerated domain of ~a to ~a"
                      (variable-name x) allowed-types)
              (remove-if-not #'(lambda (v) (member (canonical-type v) allowed-types :test #'eq))
                             enumerated-domain))))
    (unless (variable-possibly-nonreal-number? x)
      (setf enumerated-domain
            (remove-if #'(lambda (x) (and (not (realp x)) (numberp x)))
                       enumerated-domain)))
    (unless (variable-possibly-noninteger-real? x)
      (setf enumerated-domain
            (remove-if #'floatp enumerated-domain)))                 
    (unless (variable-possibly-noninteger-rational? x)
      (setf enumerated-domain
            (remove-if #'ratiop enumerated-domain)))
    (unless (variable-possibly-integer? x)
      (setf enumerated-domain (remove-if #'integerp enumerated-domain)))
    (if (variable-upper-bound x)
        (let ((upper-bound (variable-upper-bound x)))
          (setf enumerated-domain
                (remove-if #'(lambda (element) (> element upper-bound))
                           enumerated-domain))))
    (if (variable-lower-bound x)
        (let ((lower-bound (variable-lower-bound x)))
          (setf enumerated-domain
                (remove-if #'(lambda (element) (< element lower-bound))
                           enumerated-domain))))
    (when (and (variable-possibly-noninteger-rational? x)
               (variable-max-denom x))
    (setf enumerated-domain
          (remove-if #'(lambda (v)
                        (and (ratiop v)
                             (> (denominator v) (variable-max-denom x))))
                    enumerated-domain)))
    (setf enumerated-domain
          (if (eq (variable-enumerated-domain x) t)
              (set-difference enumerated-domain
                              (variable-enumerated-antidomain x)
                              :test #'generic-equal)
              (intersection (variable-enumerated-domain x) enumerated-domain
                            :test #'generic-equal)))
    (if (set-enumerated-domain! x enumerated-domain) (run-noticers x))))

(defun restrict-enumerated-antidomain! (x enumerated-antidomain)
  ;; note: X must be a variable such that (EQ X (VALUE-OF X)).
  ;; note: ENUMERATED-ANTIDOMAIN must not be a variable.
  (unless (typep enumerated-antidomain 'sequence) (fail))
  (when (every #'ground? enumerated-antidomain)
    (setf enumerated-antidomain
          (remove-duplicates
           (map 'list #'eliminate-variables enumerated-antidomain)
           :test #'generic-equal))
    (cond
      ((eq (variable-enumerated-domain x) t)
       (setf enumerated-antidomain
             (union (variable-enumerated-antidomain x) enumerated-antidomain
                    :test #'generic-equal))
       (when (> (length enumerated-antidomain)
                (length (variable-enumerated-antidomain x)))
         (local (setf (variable-enumerated-antidomain x) enumerated-antidomain))
         (run-noticers x)))
      ((set-enumerated-domain!
        x (set-difference (variable-enumerated-domain x) enumerated-antidomain
                          :test #'generic-equal))
       (run-noticers x)))))

;; new types restrictions

(defun restrict-list! (x)
 (restrict-type! x 'list))

(defun restrict-nonlist! (x)
  (restrict-nontype! x 'list))

(defun restrict-cons! (x)
  (restrict-type! x 'cons))

(defun restrict-noncons! (x)
  (restrict-nontype! x 'cons))

(defun restrict-symbol! (x)
  (restrict-type! x 'symbol))

(defun restrict-nonsymbol! (x)
  (restrict-nontype! x 'symbol))

(defun restrict-string! (x)
  (restrict-type! x 'string))

(defun restrict-nonstring! (x)
  (restrict-nontype! x 'string))

;; known?

(defun known?-typepv (x type)
  (let ((x (value-of x)))
    (typecase x
      (variable (if (not (eq (variable-nonnumber-type x) t))
                    (eq (variable-nonnumber-type x) type)
                     nil))
      (otherwise (eq (canonical-type x) type)))))

(defun known?-notv-typepv (x type)
  (let ((x (value-of x)))
    (typecase x
      (variable (if (not (eq (variable-nonnumber-type x) t))
                    (not (eq (variable-nonnumber-type x) type))
                     nil))
      (otherwise (not (eq (canonical-type x) type))))))

;; assert!- 

(defun assert!-typepv (x type)
  (let ((x (value-of x)))
    (typecase x
      (variable (restrict-type! x type))
      (otherwise (unless (eq (canonical-type x) type)
                    (fail))))))

(defun assert!-notv-typepv (x type)
  (let ((x (value-of x)))
    (typecase x
      (variable (restrict-nontype! x type))
      (otherwise (if (eq (canonical-type x) type)
                      (fail))))))

;; typepv

(defun typepv (x type)
  "Returns T if X is known to be a value of the specified type."
  (cond ((known?-typepv x type) t)
        ((known?-notv-typepv x type) nil)
        (t (let ((x (variablize x))
                 (z (a-booleanv)))
             (attach-noticer!
              #'(lambda ()
                  (cond ((variable-type? x type) (restrict-true! z))
                        ((variable-nontype? x type) (restrict-false! z))))
              x)
             (attach-noticer!
              #'(lambda ()
                  (cond ((variable-true? z) (restrict-type! x type))
                        ((variable-false? z) (restrict-nontype! x type))))
              z)
             z))))

;; transform functions

(defun-compile-time transform-known? (form polarity?)
  (if (and (consp form) (null (rest (last form))))
      (cond
        ((and (eq (first form) 'notv)
              (= (length form) 2))
         (transform-known? (second form) (not polarity?)))
        ((eq (first form) 'andv)
         (cons (if polarity? 'and 'or)
               (mapcar #'(lambda (form) (transform-known? form polarity?))
                       (rest form))))
        ((eq (first form) 'orv)
         (cons (if polarity? 'or 'and)
               (mapcar #'(lambda (form) (transform-known? form polarity?))
                       (rest form))))
        ((member (first form)
                 '(integerpv realpv numberpv memberv booleanpv
                   =v <v <=v >v >=v /=v funcallv applyv equalv)
                 :test #'eq)
         (cons (cdr (assoc (first form)
                           (if polarity?
                               '((integerpv . known?-integerpv)
                                 (rationalpv . known?-rationalpv)
                                 (ratiopv . known?-ratiopv)
                                 (floatpv . known?-floatpv)
                                 (realpv . known?-realpv)
                                 (numberpv . known?-numberpv)
                                 (memberv . known?-memberv)
                                 (booleanpv . known?-booleanpv)
                                 (typepv . known?-typepv)
                                 (=v . known?-=v)
                                 (<v . known?-<v)
                                 (<=v . known?-<=v)
                                 (>v . known?->v)
                                 (>=v . known?->=v)
                                 (/=v . known?-/=v)
                                 (funcallv . known?-funcallv)
                                 (applyv . known?-applyv)
                                 (equalv . known?-equalv))
                               '((integerpv . known?-notv-integerpv)
                                 (rationalpv . known?-notv-rationalpv)
                                 (ratiopv . known?-notv-ratiopv)
                                 (floatpv . known?-notv-floatpv)
                                 (realpv . known?-notv-realpv)
                                 (numberpv . known?-notv-numberpv)
                                 (memberv . known?-notv-memberv)
                                 (booleanpv . known?-notv-booleanpv)
                                 (typepv . known?-notv-typepv)
                                 (=v . known?-/=v)
                                 (<v . known?->=v)
                                 (<=v . known?->v)
                                 (>v . known?-<=v)
                                 (>=v . known?-<v)
                                 (/=v . known?-=v)
                                 (funcallv . known?-notv-funcallv)
                                 (applyv . known?-notv-applyv)
                                 (equalv . known?-notv-equalv)))
                           :test #'eq))
               (rest form)))
        (polarity? `(known?-true ,form))
        (t `(known?-false ,form)))
      (if polarity? `(known?-true ,form) `(known?-false ,form))))

(defun-compile-time transform-assert! (form polarity?)
  (if (and (consp form) (null (rest (last form))))
      (cond
        ((and (eq (first form) 'notv)
              (= (length form) 2))
         (transform-assert! (second form) (not polarity?)))
        ((eq (first form) 'andv)
         (if polarity?
             `(progn ,@(mapcar
                        #'(lambda (form) (transform-assert! form polarity?))
                        (rest form)))
             (cond ((null (rest form)) `(fail))
                   ((null (rest (rest form))) `(assert!-false ,(second form)))
                   (t `(assert!-notv-andv ,@(rest form))))))
        ((eq (first form) 'orv)
         (if polarity?
             (cond ((null (rest form)) `(fail))
                   ((null (rest (rest form))) `(assert!-true ,(second form)))
                   (t `(assert!-orv ,@(rest form))))
             `(progn ,@(mapcar
                        #'(lambda (form) (transform-assert! form polarity?))
                        (rest form)))))
        ((member (first form)
                 '(integerpv realpv numberpv memberv booleanpv
                   =v <v <=v >v >=v /=v funcallv applyv equalv)
                 :test #'eq)
         (cons (cdr (assoc (first form)
                           (if polarity?
                               '((integerpv . assert!-integerpv)
                                 (rationalpv . assert!-rationalpv)
                                 (ratiopv . assert!-ratiopv)
                                 (floatpv . assert!-floatpv)
                                 (realpv . assert!-realpv)
                                 (numberpv . assert!-numberpv)
                                 (memberv . assert!-memberv)
                                 (booleanpv . assert!-booleanpv)
                                 (typepv . assert!-typepv)
                                 (=v . assert!-=v)
                                 (<v . assert!-<v)
                                 (<=v . assert!-<=v)
                                 (>v . assert!->v)
                                 (>=v . assert!->=v)
                                 (/=v . assert!-/=v)
                                 (funcallv . assert!-funcallv)
                                 (applyv . assert!-applyv)
                                 (equalv . assert!-equalv))
                               '((integerpv . assert!-notv-integerpv)
                                 (rationalpv . assert!-notv-rationalpv)
                                 (ratiopv . assert!-notv-ratiopv)
                                 (floatpv . assert!-notv-floatpv)
                                 (realpv . assert!-notv-realpv)
                                 (numberpv . assert!-notv-numberpv)
                                 (memberv . assert!-notv-memberv)
                                 (booleanpv . assert!-notv-booleanpv)
                                 (typepv . assert!-notv-typepv)
                                 (=v . assert!-/=v)
                                 (<v . assert!->=v)
                                 (<=v . assert!->v)
                                 (>v . assert!-<=v)
                                 (>=v . assert!-<v)
                                 (/=v . assert!-=v)
                                 (funcallv . assert!-notv-funcallv)
                                 (applyv . assert!-notv-applyv)
                                 (equalv . assert!-notv-equalv)))
                           :test #'eq))
               (rest form)))
        (polarity? `(assert!-true ,form))
        (t `(assert!-false ,form)))
      (if polarity? `(assert!-true ,form) `(assert!-false ,form))))

(defun-compile-time transform-decide (form polarity?)
  (if (and (consp form) (null (rest (last form))))
      (cond
        ((and (eq (first form) 'notv)
              (= (length form) 2))
         (transform-decide (second form) (not polarity?)))
        ((eq (first form) 'andv)
         (let ((result (mapcar #'(lambda (form)
                                   (multiple-value-list
                                    (transform-decide form polarity?)))
                               (rest form))))
           (values (reduce #'append (mapcar #'first result))
                   (cons (if polarity? 'progn 'either)
                         (mapcar #'second result))
                   (cons (if polarity? 'either 'progn)
                         (mapcar #'third result)))))
        ((eq (first form) 'orv)
         (let ((result (mapcar #'(lambda (form)
                                   (multiple-value-list
                                    (transform-decide form polarity?)))
                               (rest form))))
           (values (reduce #'append (mapcar #'first result))
                   (cons (if polarity? 'either 'progn)
                         (mapcar #'second result))
                   (cons (if polarity? 'progn 'either)
                         (mapcar #'third result)))))
        ((member (first form)
                 '(integerpv realpv numberpv memberv booleanpv
                   =v <v <=v >v >=v /=v funcallv applyv equalv)
                 :test #'eq)
         (let ((arguments (mapcar #'(lambda (argument)
                                      (declare (ignore argument))
                                      (gensym "ARGUMENT-"))
                                  (rest form))))
           (values (mapcar #'list arguments (rest form))
                   (cons (cdr (assoc (first form)
                                     (if polarity?
                                         '((integerpv . assert!-integerpv)
                                           (rationalpv . assert!-rationalpv)
                                           (ratiopv . assert!-ratiopv)
                                           (floatpv . assert!-floatpv)
                                           (realpv . assert!-realpv)
                                           (numberpv . assert!-numberpv)
                                           (memberv . assert!-memberv)
                                           (booleanpv . assert!-booleanpv)
                                           (typepv . assert!-typepv)
                                           (=v . assert!-=v)
                                           (<v . assert!-<v)
                                           (<=v . assert!-<=v)
                                           (>v . assert!->v)
                                           (>=v . assert!->=v)
                                           (/=v . assert!-/=v)
                                           (funcallv . assert!-funcallv)
                                           (applyv . assert!-applyv)
                                           (equalv . assert!-equalv))
                                         '((integerpv . assert!-notv-integerpv)
                                           (rationalpv . assert!-notv-rationalpv)
                                           (ratiopv . assert!-notv-ratiopv)
                                           (floatpv . assert!-notv-floatpv)
                                           (realpv . assert!-notv-realpv)
                                           (numberpv . assert!-notv-numberpv)
                                           (memberv . assert!-notv-memberv)
                                           (booleanpv . assert!-notv-booleanpv)
                                           (typepv . assert!-notv-typepv)
                                           (=v . assert!-/=v)
                                           (<v . assert!->=v)
                                           (<=v . assert!->v)
                                           (>v . assert!-<=v)
                                           (>=v . assert!-<v)
                                           (/=v . assert!-=v)
                                           (funcallv . assert!-notv-funcallv)
                                           (applyv . assert!-notv-applyv)
                                           (equalv . assert!-notv-equalv)))
                                     :test #'eq))
                         arguments)
                   (cons (cdr (assoc (first form)
                                     (if polarity?
                                         '((integerpv . assert!-notv-integerpv)
                                           (realpv . assert!-notv-realpv)
                                           (numberpv . assert!-notv-numberpv)
                                           (memberv . assert!-notv-memberv)
                                           (booleanpv . assert!-notv-booleanpv)
                                           (=v . assert!-/=v)
                                           (<v . assert!->=v)
                                           (<=v . assert!->v)
                                           (>v . assert!-<=v)
                                           (>=v . assert!-<v)
                                           (/=v . assert!-=v)
                                           (funcallv . assert!-notv-funcallv)
                                           (applyv . assert!-notv-applyv)
                                           (equalv . assert!-notv-equalv))
                                         '((integerpv . assert!-integerpv)
                                           (realpv . assert!-realpv)
                                           (numberpv . assert!-numberpv)
                                           (memberv . assert!-memberv)
                                           (booleanpv . assert!-booleanpv)
                                           (=v . assert!-=v)
                                           (<v . assert!-<v)
                                           (<=v . assert!-<=v)
                                           (>v . assert!->v)
                                           (>=v . assert!->=v)
                                           (/=v . assert!-/=v)
                                           (funcallv . assert!-funcallv)
                                           (applyv . assert!-applyv)
                                           (equalv . assert!-equalv)))
                                     :test #'eq))
                         arguments))))
        (t (let ((argument (gensym "ARGUMENT-")))
             (values (list (list argument form))
                     (if polarity?
                         `(assert!-true ,argument)
                         `(assert!-false ,argument))
                     (if polarity?
                         `(assert!-false ,argument)
                         `(assert!-true ,argument))))))
      (let ((argument (gensym "ARGUMENT-")))
        (values
         (list (list argument form))
         (if polarity? `(assert!-true ,argument) `(assert!-false ,argument))
         (if polarity? `(assert!-false ,argument) `(assert!-true ,argument))))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; END OF PATCH
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
